name: xeus-octave-wasm
channels:
  # This tells the solver to look in our new local channel first
  - ./channels/local-channel
  - https://repo.prefix.dev/emscripten-forge-dev
dependencies:
  - xeus-octave-wasm
  - octave-build-static
  - xeus